apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: default
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
    - port: ${APP_PORT}
      targetPort: ${APP_CONTAINER_PORT}
  selector:
    app: chat-service
