apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DEFAULT_CONNECTION_STRING: ${{ secrets.AUTH_CONNECTION_STRING }}
  JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

