apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendship-service
  namespace: default
  labels:
    app: friendship-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendship-service
  template:
    metadata:
      labels:
        app: friendship-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: friendship-service
          image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: friendship-service-secret
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 60