# RabbitMQ
services:
  notification-db:
    image: postgres:17-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env.postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - notification_data:/var/lib/postgresql/data

volumes:
  notification_data:
