apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: ${APP_PORT}
      targetPort: ${APP_CONTAINER_PORT}
  selector:
    app: notification-service
