apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: notification-service
          image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: ${APP_CONTAINER_PORT}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          envFrom:
            - secretRef:
                name: notification-service-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: ${APP_CONTAINER_PORT}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: ${APP_CONTAINER_PORT}
            initialDelaySeconds: 15
            periodSeconds: 60
