version: "3.9"

services:
  chat-service:
    build:
      context: ../ChatService
      dockerfile: Dockerfile
    image: duongthuan0405/chat-service-dev:latest
    container_name: ${CHAT_SERVICE_CONTAINER_NAME}
    env_file:
      - .env.service
    ports:
      - "${ASPNETCORE_HOST_PORT}:${ASPNETCORE_CONTAINER_PORT}"
    volumes:
      - log_data:/app/
    depends_on:
      - postgres


  postgres:
    image: postgres:17-alpine

    container_name: ${DB_CONTAINER_NAME}

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  log_data: