services:
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: authpassword
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5073:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection='postgresql://neondb_owner:npg_7VUwhy4uZjaM@ep-nameless-fog-aoafileu-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
      - Jwt__Issuer=chat-microservices-auth-service
      - Jwt__Audience=chat-microservices-clients
      - Jwt__SigningKey=replace-this-development-key-with-a-long-random-secret
    networks:
      - auth-network

volumes:
  pgdata:

networks:
  auth-network:
    driver: bridge
