apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: default
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090
        isDefault: true
        editable: true