apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              service: "prometheus"

      - job_name: "auth-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["auth-service.default.svc.cluster.local:3667"]
            labels:
              service: "auth-service"

      - job_name: "chat-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["chat-service.default.svc.cluster.local:80"]
            labels:
              service: "chat-service"

      - job_name: "conversation-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["conversation-service.default.svc.cluster.local:8083"]
            labels:
              service: "conversation-service"

      - job_name: "friendship-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["friendship-service.default.svc.cluster.local:8081"]
            labels:
              service: "friendship-service"

      - job_name: "notification-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["notification-service.default.svc.cluster.local:80"]
            labels:
              service: "notification-service"