name: Chat Service - Push to main CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'services/chat-service/**'
      - '.github/workflows/chat-service-push-main.yml'

  workflow_dispatch:
    inputs:
      imageTag:
        description: Docker image tag
        required: true
        
jobs:
  build-publish:
    name: Build & Publish to Azure ACR
    runs-on: ubuntu-latest
    environment: ChatServiceProduction
    defaults: 
      run: 
        working-directory: ./services/chat-service/ChatService/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: services/chat-service/ChatService/ChatService.csproj

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: echo "Test if have some test cases"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=sha,format=long
            latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: services/chat-service/ChatService/
          file: services/chat-service/ChatService/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: SSH 
      
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Set AKS Context
      #   uses: azure/aks-set-context@v4
      #   with:
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}

      # - name: Substitute Environment Variables in Manifests
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_IMAGE: "${{ secrets.DOCKER_IMAGE }}"
      #     DB_HOST: "${{ secrets.DB_HOST }}"
      #     DB_PORT: "${{ secrets.DB_PORT }}"
      #     DB_USERNAME: "${{ secrets.DB_USERNAME }}"
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_DATABASE: "${{ secrets.DB_DATABASE }}"
      #     RABBITMQ_HOST: "${{ secrets.RABBITMQ_HOST }}"
      #     RABBITMQ_PORT: "${{ secrets.RABBITMQ_PORT }}"
      #     RABBITMQ_USERNAME: "${{ secrets.RABBITMQ_USERNAME }}"
      #     RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      #   run: |
      #     envsubst < k8s/deployments/chat-service/chat-service-migration-job.yaml > temp_job.yaml && mv temp_job.yaml k8s/deployments/chat-service/chat-service-migration-job.yaml
      #     envsubst < k8s/deployments/chat-service/chat-service-deployment.yaml > temp_dep.yaml && mv temp_dep.yaml k8s/deployments/chat-service/chat-service-deployment.yaml

      # - name: Deploy Database Migration Job
      #   uses: Azure/k8s-deploy@v5
      #   with:
      #     action: deploy
      #     manifests: |
      #       k8s/deployments/chat-service/chat-service-migration-job.yaml
      #     images: |
      #       ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}

      # - name: Wait for Migration to Complete
      #   run: |
      #     kubectl wait --for=condition=complete job/chat-service-migration-job --timeout=180s

      # - name: Deploy Main Application to AKS
      #   uses: Azure/k8s-deploy@v5
      #   with:
      #     action: deploy
      #     manifests: |
      #       k8s/deployments/chat-service/chat-service-deployment.yaml
      #       k8s/deployments/chat-service/chat-service-service.yaml
      #     images: |
      #       ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}

      # - name: Clean up Migration Job
      #   run: |
      #     kubectl delete job chat-service-migration-job --ignore-not-found=true