# do this jobs after a push-main job is done
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      imageTag:
        description: Docker image tag
        required: true

jobs:
  deploy:
    needs: [build-publish]
    name: Deploy API Gateway Ingress
    runs-on: ubuntu-latest
    environment: IngressProduction

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Deploying API Gateway Ingress to Kubernetes Cluster"

      - name: SSH into vps
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connected to VPS. Deploying Ingress..."
            kubectl apply -f k8s/infrastructure/api-gateway-ingress.yaml